[board]
_name = "stm32h743vit6"

[board.peripherals.spi1]
# pins = { _sck = "PA5", miso = "PA6", mosi = "PA7", int1 = "PB0", int2 = "PB1"}
clock_speed = "20MHz"

[sensors.imu]
name = "icm42688p"
interface = "SPI1"
pins = { cs = "PA4", sck = "PA5", miso = "PA6", mosi = "PA7", int1 = "PB0", int2 = "PB1"}
gyro_range = "2000_dps"
accel_range = "16_g"
sample_rate = "1000_hz"
accel_power_mode = "low_noise"

